---
resource_pools:
  - name: small
    network: vault
    stemcell: (( grab meta.stemcell ))

    cloud_properties: {}

compilation:
  network: vault
  workers: 1
  reuse_compilation_vms: true

  cloud_properties: {}

jobs:
  - name: vault
    resource_pool: small
